apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-config
  namespace: default
data:
  datasource.yaml: |
    apiVersion: 1
    kind: Datasource
    metadata:
      name: kirilldata
    spec:
      name: kirill
      type: datasource
      access: proxy
      isDefault: true
 
