grafana:
  image:
    repository: grafana/grafana
    tag: latest



  # To mount your custom datasource plugin into the Grafana pod
  volumeMounts:
    - name: my-plugin
      mountPath: /var/lib/grafana/plugins
  volumes:
    - name: my-plugin
      emptyDir: {}

      # Optionally, configure Grafana to start with a custom datasource automatically
  datasources:
    datasource.yaml:
      apiVersion: 1
      datasources:  
      - name: kirill
        type: datasource
        url: http://localhot:3000/api/health/
        access: proxy
      # Here you can configure the datasource using a .yaml file
      # Example: Adding a custom data source
      # Add the file `datasource.yaml` with the necessary configurations
      # in your Kubernetes setup (more details below)

    dashboards:
      enabled: true
      # If you want Grafana to provision dashboards automatically
      # Add your custom dashboards here
secret:
  enabled: false      

# For Kubernetes Service configuration
service:
  type: LoadBalancer  # Or NodePort if you are using Minikube or a local cluster
  port: 3000